/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package form;

import java.sql.*;
import Team.performRanking;
import java.util.ArrayList;
import model.Model_playerRanking;
import Team.performRanking.player;
import swing.ScrollBar;


/**
 *
 * @author user
 */
public class Form_7 extends javax.swing.JPanel {

    /**
     * Creates new form Form_7
     */
    public Form_7() {
    initComponents();
    sp.setVerticalScrollBar(new ScrollBar());
    sp.setHorizontalScrollBar(new ScrollBar());
    
    performRanking pr = new performRanking();
    try (Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3308/java_user_database", "root", "")) {
        pr.initialise(conn, "1");
        pr.fetchPlayers();

        ArrayList<performRanking.player> sortedPlayers = pr.getPlayerList();
        int rank = 1;
        
        for (performRanking.player p : sortedPlayers) {
            Model_playerRanking modelPlayer = new Model_playerRanking(p.getPlayerID(), rank++, p.getGames(), p.getName(), p.getPosition(), p.getCompositeScore(), p.getSteals(), p.getBlocks(), p.getRebounds(), p.getAssists());
            System.out.println(modelPlayer);
            
            // Add modelPlayer to panelRank
            panelRank.add(modelPlayer);
        }
    } catch (SQLException ex) {
        System.out.println(ex);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        sp = new javax.swing.JScrollPane();
        panelRank = new swing.PanelBorder();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,80));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("-- Player Performance Ranking --");

        panelRank.setBackground(new java.awt.Color(255, 255, 255));
        panelRank.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelRankLayout = new javax.swing.GroupLayout(panelRank);
        panelRank.setLayout(panelRankLayout);
        panelRankLayout.setHorizontalGroup(
            panelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        panelRankLayout.setVerticalGroup(
            panelRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        sp.setViewportView(panelRank);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(sp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        add(jPanel1);
        jPanel1.setBounds(120, 40, 750, 580);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/background1.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(-140, -60, 1190, 760);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private swing.PanelBorder panelRank;
    private javax.swing.JScrollPane sp;
    // End of variables declaration//GEN-END:variables
}
